FROM microsoft/dotnet:2.1.0-runtime

WORKDIR /app

ENV XML_STATION_CONFIG=/app/GDM_TestConfiguration.xml
ENV CFG_SETTINGS_LOCATION="/settings/"

ENV http_proxy=http://ip:9400/
ENV https_proxy=http://ip:9400/

RUN mkdir -p /usr/share/man/man1 \
&& mkdir -p /usr/share/man/man7 \
&& apt-get update \ 
&& apt-get install -y --no-install-recommends \
nano \
postgresql-client \
&& rm -rf /var/lib/apt/lists/*

#unset PROXY
ENV http_proxy=""
ENV https_proxy=""

VOLUME ["/settings/"]

COPY ./publish_CONF /app

RUN cp /app/init.sh / && chmod 755 /init.sh

ENTRYPOINT ["/init.sh"]

